docs: updates README.md with Getting Started and design info
RedHatProductSecurity/oscal-profiles pull request #91
Opened 2024-05-20 18:44 UTC by jpower432

Updates docs to use the same structure as `oscal-component-definitions`. This replaces the manual tutorial (which is out of date) with a tutorial about how to interact with the repostiroy content through GitHub and `trestle-bot` actions. In depth approach information (like https://github.com/RedHatProductSecurity/oscal-component-definitions/blob/main/docs/design.md) is also added.

2024-05-21 17:47 UTC, gvauter requested changes

2024-05-21 17:47 UTC, gvauter commented on README.md
> +2. A user submits a pull request to add their changes to the workspace's master branch.
Suggest replacing `master` with `main` to align with step 4.

2024-05-21 17:47 UTC, gvauter commented on docs/design.md
> +#### AutoFix
Would it ease understanding if this was titled "AutoSync" to align with the trestle-bot terminology?

2024-05-22 19:00 UTC, jpower432 commented
@gvauter Please take another look. Due to changes in the CI files, this might require some testing on my fork as well.

2024-05-23 15:00 UTC, gvauter approved these changes
LGTM

2024-05-23 16:22 UTC, merged